appMessage: Test Fr2 Transcation Engine Micro service. value updated for demo.
---
spring:
  profiles: qaps
appMessage: QAPS Transcation Engine Micro service 
---
spring:
  profiles: prod
appMessage: PROD Transcation Engine Micro service 
